Add an option to remove unused requests from cassette
kevin1024/vcrpy pull request #763
Opened 2023-08-20 13:28 UTC by danielnsilva

This PR adds an option to remove previously recorded interactions if they are not used. I believe this feature can address the issue discussed in #208. We don't need to focus on ignoring all requests in the cassette file, but instead, we can write to file only replayed interactions and new ones. If no previous request is used, VCR will save only new interactions.

There is a [similar feature](https://github.com/vcr/vcr/pull/946) in Ruby VCR.

Replaces #677

2025-01-04 18:58 UTC, jairhenrique commented
LGTM 🚀 

@danielnsilva can you fix some lint erros?

2025-01-08 19:05 UTC, jairhenrique approved these changes

2025-01-08 19:06 UTC, jairhenrique commented
@hartwork can you help review this pull request?

2025-01-10 00:56 UTC, hartwork requested changes

2025-01-10 00:56 UTC, hartwork commented on vcr/cassette.py
> +            force = True
Is this addition missing a check for `drop_unused_requests`?

2025-01-10 00:56 UTC, hartwork commented on vcr/cassette.py
> +            responses = [response for _, response in interactions]
This behavior seems unexpected in a method `_as_dict` from a user point of view. Can this behavior be moved elsewhere?

2025-01-10 00:56 UTC, hartwork commented on docs/advanced.rst
> +        # your http here
```suggestion
        ...  # your HTTP interactions here
```
?

(to make it valid Python)

2025-01-11 15:58 UTC, danielnsilva commented on vcr/cassette.py
> +            force = True
You're right, it does need a check for drop_unused_requests.

2025-01-11 16:29 UTC, danielnsilva commented on vcr/cassette.py
> +            responses = [response for _, response in interactions]
A better approach might be to move it to the `_save` method.

```python
def _as_dict(self):
    return {"requests": self.requests, "responses": self.responses}

def _build_used_interactions_dict(self):
    interactions = self._played_interactions + self._new_interactions()
    cassete_dict = {
        "requests": [request for request, _ in interactions],
        "responses": [response for _, response in interactions],
    }
    return cassete_dict

def _save(self, force=False):
    if self.drop_unused_requests and len(self._played_interactions) < len(self._old_interactions):
        cassete_dict = self._build_used_interactions_dict()
        force = True
    else:
        cassete_dict = self._as_dict()
    if force or self.dirty:
        self._persister.save_cassette(self._path, cassete_dict, serializer=self._serializer)
        self.dirty = False
```

2025-01-11 16:33 UTC, hartwork commented on vcr/cassette.py
> +            responses = [response for _, response in interactions]
@danielnsilva looks like a good idea to me! :+1:

2025-01-11 19:51 UTC, hartwork approved these changes
@danielnsilva thanks for the adjustments! :+1:

2025-01-11 19:51 UTC, merged